Hometask 1 and 2
EKovtun/smart-home-2020 pull request #1
Opened 2020-10-02 00:15 UTC by EKovtun

2020-10-09 13:54 UTC, a-ivanov requested changes

2020-10-09 13:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smart/home/utils/SmartHomeReaderWriter.java
> +    SmartHome loadSmartHome() throws RuntimeException;
> RuntimeException and its subclasses are unchecked exceptions. Unchecked exceptions do not need to be declared in a method or constructor's throws clause if they can be thrown by the execution of the method or constructor and propagate outside the method or constructor boundary

Не надо объявлять RuntimeException

2020-10-09 13:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +    private SmartHome smartHome;
Можно сделать локальной переменной метода run

2020-10-09 13:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        while(true) {
https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#%D0%BF%D0%B5%D1%80%D0%B5%D0%BD%D0%B5%D1%81%D0%B8%D1%82%D0%B5-%D0%BB%D0%BE%D0%B3%D0%B8%D0%BA%D1%83-%D1%86%D0%B8%D0%BA%D0%BB%D0%B0-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B8-%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B9-%D0%B2-%D0%BE%D1%82%D0%B4%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9-%D0%BA%D0%BB%D0%B0%D1%81%D1%81

2020-10-09 13:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +                System.out.printf("Device id '%s' is not exist%n", event.getObjectId());
Это не ответственность цикла - проверять присутствие объекта в доме.

2020-10-09 13:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/EventManager.java
> +    public SensorEvent getNextSensorEvent() {
1. Зачем этот метод в этом классе, если API класса, судя по коду, это executeEvent?
2. Генерация событий - отдельная ответственность, перенесите в отдельный класс.

2020-10-09 13:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/SensorEventType.java
> +    LIGHT_ON(new ActionLightOn()),
А если мы захотим добавить несколько действий на одно событие? Тут нарушен OCP.
Для этого и лучше разделить на классы: событие, обработчик, действие, цикл обработки.

2020-10-09 13:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smart/home/SmartHome.java
> +    public Collection<SmartDevice> getAllDevices(Location location) {
Привязываемся в API к внутренней структуре дома - клиент оперирует Location.

2020-10-09 13:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smart/home/SmartHome.java
> +    public Collection<SmartDevice> getAllDevices(Location location) {
https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-2 нужен внутренний итератор для ухода этого

2020-10-09 13:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smart/actions/ActionLightOn.java
> +        if (smartDevice == null || smartDevice.getType() != SmartDeviceType.LIGHT) return;
Проверка instanseof проще, чем добавление значений в SmartDeviceType (которые будут дублировать классы).

2020-10-09 13:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smart/actions/ActionLightOn.java
> +public class ActionLightOn implements Action {
https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#%D0%BF%D1%80%D0%B8%D0%B4%D0%B5%D1%80%D0%B6%D0%B8%D0%B2%D0%B0%D0%B9%D1%82%D0%B5%D1%81%D1%8C-%D0%BF%D1%80%D0%B5%D0%B4%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%BD%D1%8B%D0%BC-%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0%D0%BC-action-%D0%B8-actionable

2020-10-09 13:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smart/devices/SmartDevice.java
> +public interface SmartDevice extends Actionable {
Зачем extends? Можно имплементировать дв интерфейса отдельно друг от друга.

2020-10-09 13:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smart/home/SmartHome.java
> +        action.act(this);
А где реализация composite паттерна по 2 дз?

2020-10-09 13:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smart/home/locations/Room.java
> +public class Room implements Location {
https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D1%83%D0%B9%D1%82%D0%B5%D1%81%D1%8C-%D1%82%D0%B5%D0%BA%D1%83%D1%89%D0%B5%D0%B9-%D0%B8%D0%B5%D1%80%D0%B0%D1%80%D1%85%D0%B8%D0%B5%D0%B9-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BE%D0%B2-%D0%B4%D0%BE%D0%BC%D0%B0

2020-10-09 13:54 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smart/home/locations/Room.java
> +public class Room implements Location {
Тут могла бы быть реализация composite паттерна по 2 дз

2020-10-10 19:37 UTC, EKovtun commented on src/main/java/ru/sbt/mipt/oop/events/SensorEventType.java
> +    LIGHT_ON(new ActionLightOn()),
Можно добавить больше действий через запятую. 
Я не понимаю в чём нарушен OCP.
Такое решение очень удобно использовать, привязывая действия, которые должны быть выполнены при ивенте.

2020-10-10 19:42 UTC, EKovtun commented on src/main/java/ru/sbt/mipt/oop/smart/home/SmartHome.java
> +    public Collection<SmartDevice> getAllDevices(Location location) {
Зачем обходить все девайся дома итерационно?
Если девайсов очень много - это абсолютно неоптимальное решение, каждый элемент потребуется просмотреть и провести сравнение с его локацией.
Словарь не занимает много места, а если пользователю потребуется получить девайся по какой-либо локации - мы выдадим их ему за константу.
А если системе потребуется довольно часто получать девайся по локации? Это же дикая просадка по скорости.

2020-10-12 23:35 UTC, a-ivanov requested changes

2020-10-12 23:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smart/home/utils/SmartHomeReaderWriter.java
> +    SmartHome loadSmartHome() throws IOException;
Я бы сказал, что это нарушение ISP. Нам разве нужно читать и однвоременно записывать в логике приложения?

2020-10-12 23:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smart/home/utils/SmartHomeReaderWriter.java
> +    SmartHome loadSmartHome() throws IOException;
https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#%D0%BD%D0%B5-%D0%B4%D0%B0%D0%B2%D0%B0%D0%B9%D1%82%D0%B5-%D0%B0%D0%B1%D1%81%D1%82%D1%80%D0%B0%D0%BA%D1%86%D0%B8%D0%B8-%D1%82%D0%B5%D1%87%D1%8C

2020-10-12 23:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/EventGenerator.java
> +public class EventGenerator {
Можно выделить интерфейс, чтобы потом было легче заменить на "настоящую" имплементацию генератора событий.

2020-10-12 23:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/EventProcessor.java
> +            case DOOR_CLOSED:
Нарушение OCP, ведь для этого есть отдельные обработчики.

2020-10-12 23:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/EventProcessor.java
> +            if (deviceRoom != null && deviceRoom.getName().equals("hall"))
Это responsibility отдельного обработчика события холла

2020-10-12 23:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/actions/Action.java
> +    String getDeviceId();
getDeviceId явно лишний метод в этом API.

2020-10-12 23:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smart/home/Room.java
> +    public Collection<SmartDevice> getDevices() {
Этого метода по 2 дз быть не должно https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5-2

2020-10-12 23:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smart/home/Room.java
> +    public void addDevice(SmartDevice device) throws IllegalArgumentException {
Лучше вообще исключать муаторы в классе. Если очень хочется, тогда они доложны быть package-private видимости.

2020-10-12 23:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smart/home/Room.java
> +    public void addDevice(SmartDevice device) throws IllegalArgumentException {
https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#%D1%81%D0%B4%D0%B5%D0%BB%D0%B8%D1%82%D0%B5-%D0%B7%D0%B0-%D0%B2%D0%B8%D0%B4%D0%B8%D0%BC%D0%BE%D1%81%D1%82%D1%8C%D1%8E-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%BE%D0%B2

2020-10-12 23:35 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smart/home/Room.java
> +            ((Actionable) device).execute(action);
Странный каст, а если device не Actionable? Тогда cast exception.
Тогда уже лучше явно ссылку на Door и Light - это вполне понятно в этой доменной модели.
Пользы от SmartDevice не очень заметно.

2020-10-12 23:35 UTC, a-ivanov commented
Пока замечания по 1-2 дз.

2020-10-16 12:36 UTC, a-ivanov requested changes

2020-10-16 12:36 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/smart/devices/Alarm.java
> +    private enum AlarmStates{
Эвалюция имплементации шаблона состояние:
1. if else по boolean
2. if else / switch по enum
3. интерфейс состояния + имплементация (как в Gang of Four).

В 3 дз предлагаю сделать пункт 3.

2020-10-16 12:37 UTC, a-ivanov requested changes

2020-10-16 12:37 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/processors/SecurityProcessorDecorator.java
> +public class SecurityProcessorDecorator implements EventProcessor {
Отправка сигнализации еще.

2020-10-22 21:38 UTC, a-ivanov requested changes

2020-10-22 21:38 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/processors/SecurityProcessorDecorator.java
> +        if (alarm.isAlert()) {
Сейчас в тревожном состоянии на каждое соыбтие будет отправляться по смс. Надо, чтобы на все обработчики приходило 1 смс.

2020-10-22 21:38 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/processors/SecurityProcessorDecorator.java
> +        if (alarm.isAlert()) {
https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#%D1%81%D0%B4%D0%B5%D0%BB%D0%B0%D0%B9%D1%82%D0%B5-%D0%BE%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%BA%D1%83-%D0%BC%D0%B0%D0%BA%D1%81%D0%B8%D0%BC%D1%83%D0%BC-%D0%BE%D0%B4%D0%BD%D0%BE%D0%B3%D0%BE-%D1%81%D0%BC%D1%81-%D0%B8%D0%B7-%D0%B4%D0%B5%D0%BA%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%B0

2020-10-26 11:46 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/processors/SecurityProcessorDecorator.java
> +        if (alarm.isAlert()) return;
Тут по зданию тоже надо отправлять смс.
Т.е. смс должно отправляться при `isAlert` тоже.
Сейчас у вас по SecurityProcessorDecorator на каждый обработчик. Т.е. при каждом новом событии при `isAlert` смс будет отправляться от каждого обработчика. А надо, чтобы при поступлении нового события на все обработчики отправлялось 1 смс.

2020-11-06 19:44 UTC, a-ivanov approved these changes

2020-11-09 00:08 UTC, merged