Hometask 4
EKovtun/smart-home-2020 pull request #2
Opened 2020-10-24 17:08 UTC by EKovtun

2020-11-06 19:53 UTC, a-ivanov requested changes

2020-11-06 19:53 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/adapter/DoorSensorEventFactory.java
> +        switch (typeName) {
Лучше заменить на мапу `Map<String, SensorEventType>` и сконфигурировать ее бином.
Тогда можно сделать единую имплементацию `SensorEventFactory`, например `MapBasedSensorEventFactory`.

2020-11-13 23:30 UTC, EKovtun commented on src/main/java/ru/sbt/mipt/oop/events/adapter/DoorSensorEventFactory.java
> +        switch (typeName) {
Я исправил так, как ты сказал, но у меня вопрос:
Я сделал bean для моей мапы и дал ей имя.
В классе фабрике на мапу навешал @Autowired и @Qualifier этого бина.
Но она падает с ошибкой, что не может найти такой Qualifier.
При том если просто у бина и у фабрике поменять тип с map на hashMap - то всё работает.
Не могу понять в чем прикол.

2020-11-14 12:21 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/adapter/DoorSensorEventFactory.java
> +        switch (typeName) {
Я думаю потому, что у тебя в MapBasedSensorEventFactory поле mapTypes - конкретного класса HashMap.
А в конфигурации ты объявляешь бин типа Map.
Поэтому лучше поля в классах объявлять интерфейсами - т.е. класс клиент не знает детали реализации.
Т.е. у тебя просто Map<...>, без деталей, что это HashMap (может мы захотим упорядочивание по ключам и заменим на TreeMap).

2020-11-14 12:26 UTC, a-ivanov approved these changes

2020-11-14 12:26 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/adapter/MapBasedSensorEventFactory.java
> +    private HashMap<String, SensorEventType> mapTypes;
Лучше не объявлять поля классом, если у класса есть интерфейс, API которого достаточно для использования в логике класса.
Тут лучше объявить `Map <String, SensorEventType>`, тогда бин, объявленный тобой как `Map<...>` найдется спрингом.

2020-11-14 12:26 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/MyConfiguration.java
> +    HashMap<String, SensorEventType> mapSensorEventTypeForFactory() {
В классе поле типа `HashMap`. Будет `Map` - найдется.
В полях/аргументах конструктора `@Autowired` даже не обязателен в современной версии спринга.

2020-11-14 13:25 UTC, EKovtun commented on src/main/java/ru/sbt/mipt/oop/MyConfiguration.java
> +    HashMap<String, SensorEventType> mapSensorEventTypeForFactory() {
Да в том то и дело, что не находит.
Если изменить HashMap на Map здесь и в MapBasedSensorEventFactory - то не находит.
А если HashMap оставить, то всё ок.
Вот я не пойму почему она так себя ведёт?

2020-11-14 13:26 UTC, EKovtun commented on src/main/java/ru/sbt/mipt/oop/MyConfiguration.java
> +    HashMap<String, SensorEventType> mapSensorEventTypeForFactory() {
Может это как-то связано что Map - это интерфейс, а HashMap - класс... я хз

2020-11-14 13:55 UTC, a-ivanov approved these changes

2020-11-14 13:55 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/events/adapter/MapBasedSensorEventFactory.java
> +    private Map<String, SensorEventType> mapTypes;
Здесь private final, поскольку поле менять ссылку не будет.

2020-11-16 09:10 UTC, merged