Hometask 5
EKovtun/smart-home-2020 pull request #3
Opened 2020-10-31 19:23 UTC by EKovtun

2020-11-13 13:26 UTC, a-ivanov requested changes
Надо сконфигурировать объекты, связанные с пультом, в конфигурации спринга, см. https://github.com/iagoshkov/smart-home-2020/blob/master/STUDENT_GUIDE.md#задание-5

2020-11-13 13:26 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/rc/MyRemoteControl.java
> +    private final HashMap<String, ControlCommand> commands = new HashMap<>();
Лучше `Map<String, ControlCommand> commands = new HashMap<>()` поле без деталей реализации.
А еще лучше - передавать сюда готовую `Map<String, ControlCommand>` через конструктор.

2020-11-13 23:36 UTC, EKovtun commented on src/main/java/ru/sbt/mipt/oop/rc/MyRemoteControl.java
> +    private final HashMap<String, ControlCommand> commands = new HashMap<>();
Я перепишу на бины и инъекцию, когда разберусь с проблемой из прошлой домашки (четвертой).
Я описал проблему в её мердж-реквесте.

2020-11-14 12:32 UTC, a-ivanov requested changes
Нужно добавить регистрацию пульта в конфигурацию спринга.

2020-11-14 12:32 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/rc/MyRemoteControl.java
> +    public void registerCommand(String buttonCode, ControlCommand command) {
Зачем лишний мутатор? Готовой мапы в конструкторе хватает, поскольку у нас нет задачи runtime добавления команд.

2020-11-14 12:32 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/rc/commands/ControlCommandActivateAlarm.java
> +public class ControlCommandActivateAlarm implements ControlCommand {
Смысл команды - альтернативный способ запуска действий.
Он не должен быть связан с логикой обработчиков.
Например, мы поменяем что-то в реализации/API обработчиков, и это может заставить нас переписывать этот код.

2020-11-14 18:00 UTC, a-ivanov requested changes
Еще необходимо создать бин RemoteControlRegistry и зарегистрировать там вашу имплементацию RemoteControl. Доставать отдельно бин RemoteControl не обязательно.

2020-11-14 18:00 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        RemoteControl myRemoteControl = context.getBean(RemoteControl.class);
Это не обязательно. Создание регистра пульта и регистрации там достаточно.

2020-11-16 08:12 UTC, a-ivanov approved these changes

2020-11-16 09:11 UTC, merged